from enum import Enum

class EventType(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    CHECKOUT_ABANDONED = "CHECKOUT_ABANDONED"
    INVOICE_OVERDUE = "INVOICE_OVERDUE"
    SUBSCRIPTION_PAYMENT_FAILED = "SUBSCRIPTION_PAYMENT_FAILED"
    PROMISE_TO_PAY_BROKEN = "PROMISE_TO_PAY_BROKEN"
    MANDATE_PAYMENT_FAILED = "MANDATE_PAYMENT_FAILED"

class CaseType(str, Enum):
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    PROMISE_TO_PAY_BROKEN = "PROMISE_TO_PAY_BROKEN"

class CaseState(str, Enum):
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    DIAGNOSED = "DIAGNOSED"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    GUARDIAN_REVIEW = "GUARDIAN_REVIEW"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"
    CLOSED = "CLOSED"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
