"""Phase 2 models

Revision ID: 2545a2a1bf32
Revises: 
Create Date: 2026-08-27 22:50:22.829118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2545a2a1bf32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('case_type', sa.Enum('PAYMENT_FAILURE', 'CHECKOUT_ABANDONMENT', 'OVERDUE_RECEIVABLE', name='casetype'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('amount_at_risk', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'ANALYZING', 'DIAGNOSED', 'STRATEGY_SELECTED', 'GUARDIAN_REVIEW', 'APPROVED', 'BLOCKED', 'EXECUTING', 'VERIFYING', 'RECOVERED', 'FAILED', 'ESCALATED', 'STOPPED', 'CLOSED', name='casestate'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=True),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('recovered_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_case_id'), 'recovery_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_recovery_cases_customer_id'), 'recovery_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_merchant_id'), 'recovery_cases', ['merchant_id'], unique=False)
    op.create_table('recovery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('PAYMENT_FAILED', 'CHECKOUT_ABANDONED', 'INVOICE_OVERDUE', 'SUBSCRIPTION_PAYMENT_FAILED', 'PROMISE_TO_PAY_BROKEN', 'MANDATE_PAYMENT_FAILED', name='eventtype'), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_events_customer_id'), 'recovery_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_events_event_id'), 'recovery_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_recovery_events_idempotency_key'), 'recovery_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_recovery_events_merchant_id'), 'recovery_events', ['merchant_id'], unique=False)
    op.create_table('case_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_audit_events_case_id'), 'case_audit_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_audit_events_case_id'), table_name='case_audit_events')
    op.drop_table('case_audit_events')
    op.drop_index(op.f('ix_recovery_events_merchant_id'), table_name='recovery_events')
    op.drop_index(op.f('ix_recovery_events_idempotency_key'), table_name='recovery_events')
    op.drop_index(op.f('ix_recovery_events_event_id'), table_name='recovery_events')
    op.drop_index(op.f('ix_recovery_events_customer_id'), table_name='recovery_events')
    op.drop_table('recovery_events')
    op.drop_index(op.f('ix_recovery_cases_merchant_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_customer_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_case_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
